"""ULPF - Universal Log Pre-processing Framework.

Ingest, parse, normalize and standardize logs and events generated by any
hardware or software system into a lossless, analytics-ready universal event
schema - with full traceability back to the original raw event.
"""

__version__ = "1.0.0"
__all__ = ["__version__"]
