```powershell
param(
    [string]$InstallDir = "$([Environment]::GetFolderPath('ProgramFiles'))\ULPF-Agent",
    [string]$DataDir = "$([Environment]::GetFolderPath('CommonApplicationData'))\ULPF-Agent",
    [string]$ServiceName = "ULPFAgent",
    [string]$Gateway = "http://127.0.0.1:5173",
    [switch]$NoService
)

$ErrorActionPreference = "Stop"

Write-Host "PARAM BLOCK OK" -ForegroundColor Green

function Find-Python {
    $candidates = @(
        @{ Command = "py"; Args = @("-3") },
        @{ Command = "python"; Args = @() },
        @{ Command = "python3"; Args = @() }
    )

    foreach ($candidate in $candidates) {
        try {
            $versionText = & $candidate.Command @($candidate.Args) `
                -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')" `
                2>$null

            if ($LASTEXITCODE -eq 0 -and $versionText) {
                $parts = $versionText.Trim().Split('.')

                if (
                    [int]$parts[0] -gt 3 -or
                    (
                        [int]$parts[0] -eq 3 -and
                        [int]$parts[1] -ge 9
                    )
                ) {
                    return @{
                        Command = $candidate.Command
                        Args    = $candidate.Args
                    }
                }
            }
        }
        catch {
        }
    }

    return $null
}

Write-Host ""
Write-Host "===============================================" -ForegroundColor Green
Write-Host "          ULPF AGENT PLUGIN INSTALLER" -ForegroundColor Green
Write-Host "===============================================" -ForegroundColor Green
Write-Host ""

# ---------------------------------------------------------
# OS DETECTION
# ---------------------------------------------------------

Write-Step "Detecting operating system..."

if ($env:OS -ne "Windows_NT") {
    throw "This installer is for Windows only."
}

$os = Get-CimInstance Win32_OperatingSystem
$arch = $env:PROCESSOR_ARCHITECTURE

Write-Host "  OS           : $($os.Caption)"
Write-Host "  Architecture : $arch"
Write-Host "  Hostname     : $env:COMPUTERNAME"

# ---------------------------------------------------------
# PYTHON
# ---------------------------------------------------------

Write-Step "Checking runtime..."

$python = Find-Python

if (-not $python) {
    throw "Python 3.9+ was not found. Install Python 3.9+ and rerun."
}

Write-Host "  Python       : $($python.Command) $($python.Args -join ' ')"

# ---------------------------------------------------------
# SOURCE AGENT
# ---------------------------------------------------------

$sourceAgent = Join-Path $PSScriptRoot "agent"

if (-not (Test-Path (Join-Path $sourceAgent "agent.py"))) {
    throw "Agent source not found: $sourceAgent"
}

# ---------------------------------------------------------
# DIRECTORIES
# ---------------------------------------------------------

Write-Step "Creating installation directories..."

New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
New-Item -ItemType Directory -Force -Path $DataDir | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $DataDir "state") | Out-Null

# ---------------------------------------------------------
# INSTALL AGENT
# ---------------------------------------------------------

Write-Step "Installing ULPF Agent files..."

$targetAgent = Join-Path $InstallDir "agent"

if (Test-Path $targetAgent) {
    Remove-Item $targetAgent -Recurse -Force
}

Copy-Item `
    -Path $sourceAgent `
    -Destination $InstallDir `
    -Recurse `
    -Force

# ---------------------------------------------------------
# CONFIGURATION
# ---------------------------------------------------------

$configPath = Join-Path $DataDir "agent.yaml"
$stateDir = Join-Path $DataDir "state"
$spoolPath = Join-Path $stateDir "spool.db"
$offsetPath = Join-Path $stateDir "offsets.json"
$agentIdPath = Join-Path $stateDir "agent-id"

$config = @"
# ULPF Agent configuration generated by the installer.

gateway: "$Gateway"
token: "Tnikita1800"
name: ""

agent_id_file: "$($agentIdPath.Replace('\','/'))"
spool: "$($spoolPath.Replace('\','/'))"
offset_file: "$($offsetPath.Replace('\','/'))"

# Windows collectors
windows_eventlog: true

windows_channels:
  - "System"
  - "Application"
  - "Security"
  - "Microsoft-Windows-PowerShell/Operational"

# File collection can be configured after installation.
files: []
directories: []
journald: false

poll_interval: 2
windows_poll_interval: 5
send_interval: 0.5
batch_size: 100
heartbeat_interval: 10
"@

Set-Content `
    -Path $configPath `
    -Value $config `
    -Encoding UTF8

# ---------------------------------------------------------
# INSTALLATION MANIFEST
# ---------------------------------------------------------

$manifest = @{
    product         = "ULPF Agent"
    version         = "1.0.0"
    service_name    = $ServiceName
    install_dir     = $InstallDir
    data_dir        = $DataDir
    config          = $configPath
    installed_at_utc = (Get-Date).ToUniversalTime().ToString("o")
    os              = $os.Caption
    architecture    = $arch
} | ConvertTo-Json -Depth 4

Set-Content `
    -Path (Join-Path $DataDir "install-manifest.json") `
    -Value $manifest `
    -Encoding UTF8

# ---------------------------------------------------------
# WINDOWS SERVICE
# ---------------------------------------------------------

if (-not $NoService) {

    Write-Step "Registering Windows service..."

    # Resolve real Python executable.
    # Windows SCM should use python.exe, not py.exe.
    $pythonExe = $python.Command

    if ($pythonExe -eq "py") {

        $pythonExe = & py -3 `
            -c "import sys; print(sys.executable)" `
            2>$null

        if ($LASTEXITCODE -ne 0 -or -not $pythonExe) {
            throw "Could not resolve the real Python executable."
        }
    }
    else {

        $pythonExe = (
            Get-Command $pythonExe -ErrorAction Stop
        ).Source
    }

    $pythonExe = $pythonExe.Trim()

    $agentPath = Join-Path $targetAgent "agent.py"

    # Validate everything before touching Windows SCM.
    if (-not (Test-Path $pythonExe)) {
        throw "Python executable not found: $pythonExe"
    }

    if (-not (Test-Path $agentPath)) {
        throw "Agent script not found: $agentPath"
    }

    if (-not (Test-Path $configPath)) {
        throw "Agent configuration not found: $configPath"
    }

    Write-Host "  Python       : $pythonExe"
    Write-Host "  Agent        : $agentPath"
    Write-Host "  Config       : $configPath"
    Write-Host "  Service      : $ServiceName"

    # -----------------------------------------------------
    # Build service command
    # -----------------------------------------------------

    $binPath = "`"$pythonExe`" `"$agentPath`" --config `"$configPath`""

    Write-Host ""
    Write-Host "  Service command:" -ForegroundColor DarkGray
    Write-Host "  $binPath" -ForegroundColor DarkGray
    Write-Host ""

    # -----------------------------------------------------
    # Remove previous service
    # -----------------------------------------------------

    Write-Host "  Removing previous service if present..."

    $existingService = Get-Service `
        -Name $ServiceName `
        -ErrorAction SilentlyContinue

    if ($existingService) {

        if ($existingService.Status -eq "Running") {

            Write-Host "  Stopping existing service..."

            & sc.exe stop $ServiceName 2>&1 | Out-Null

            Start-Sleep -Seconds 2
        }

        Write-Host "  Deleting existing service..."

        & sc.exe delete $ServiceName 2>&1 | Out-Null

        Start-Sleep -Seconds 2
    }

    # -----------------------------------------------------
    # CREATE SERVICE
    # -----------------------------------------------------

    Write-Host "  Creating Windows service..."

    # IMPORTANT:
    # Every sc.exe option is passed as ONE PowerShell argument.
    # The space after '=' is required by Windows sc.exe.
    $createArgs = @(
        "create"
        $ServiceName
        "binPath= $binPath"
        "start= auto"
        "type= own"
    )

    $createOutput = & sc.exe @createArgs 2>&1
    $createExitCode = $LASTEXITCODE

    if ($createExitCode -ne 0) {

        Write-Host ""
        Write-Host "ERROR: Windows service creation failed." -ForegroundColor Red
        Write-Host ""

        Write-Host "sc.exe output:" -ForegroundColor Yellow

        $createOutput | ForEach-Object {
            Write-Host $_ -ForegroundColor Red
        }

        Write-Host ""

        throw "Failed to create Windows service '$ServiceName'."
    }

    Write-Host "  Service created successfully." -ForegroundColor Green

    # -----------------------------------------------------
    # DISPLAY NAME
    # -----------------------------------------------------

    Write-Host "  Setting display name..."

    $displayOutput = & sc.exe config $ServiceName `
        "DisplayName= ULPF Collector Agent" `
        2>&1

    if ($LASTEXITCODE -ne 0) {

        Write-Host "  WARNING: Could not set display name." `
            -ForegroundColor Yellow
    }

    # -----------------------------------------------------
    # DESCRIPTION
    # -----------------------------------------------------

    Write-Host "  Setting service description..."

    $descriptionOutput = & sc.exe description $ServiceName `
        "ULPF local telemetry collector and registration agent" `
        2>&1

    if ($LASTEXITCODE -ne 0) {

        Write-Host "  WARNING: Could not set service description." `
            -ForegroundColor Yellow
    }

    # -----------------------------------------------------
    # SERVICE RECOVERY
    # -----------------------------------------------------

    Write-Host "  Configuring service recovery..."

    $failureOutput = & sc.exe failure $ServiceName `
        "reset= 86400" `
        "actions= restart/5000/restart/10000/restart/30000" `
        2>&1

    if ($LASTEXITCODE -ne 0) {

        Write-Host "  WARNING: Could not configure service recovery." `
            -ForegroundColor Yellow
    }

    # -----------------------------------------------------
    # VERIFY SERVICE EXISTS
    # -----------------------------------------------------

    Write-Host "  Verifying service registration..."

    $service = Get-Service `
        -Name $ServiceName `
        -ErrorAction SilentlyContinue

    if (-not $service) {

        Write-Host ""
        Write-Host "ERROR: Service was not registered." `
            -ForegroundColor Red

        throw "Windows service verification failed."
    }

    Write-Host "  Service registered successfully." `
        -ForegroundColor Green

    # -----------------------------------------------------
    # START SERVICE
    # -----------------------------------------------------

    Write-Host "  Starting service..."

    $startOutput = & sc.exe start $ServiceName 2>&1
    $startExitCode = $LASTEXITCODE

    if ($startExitCode -ne 0) {

        Write-Host ""
        Write-Host "ERROR: Windows service could not be started." `
            -ForegroundColor Red

        Write-Host ""
        Write-Host "sc.exe output:" -ForegroundColor Yellow

        $startOutput | ForEach-Object {
            Write-Host $_ -ForegroundColor Red
        }

        Write-Host ""
        Write-Host "Service configuration:" -ForegroundColor Yellow

        & sc.exe qc $ServiceName

        throw "Failed to start Windows service '$ServiceName'."
    }

    # Give SCM a moment to update the state.
    Start-Sleep -Seconds 3

    $service = Get-Service `
        -Name $ServiceName `
        -ErrorAction SilentlyContinue

    if (-not $service) {
        throw "Service disappeared after start."
    }

    # -----------------------------------------------------
    # FINAL SERVICE STATUS
    # -----------------------------------------------------

    Write-Host ""
    Write-Host "  Service      : $ServiceName" -ForegroundColor Green
    Write-Host "  Status       : $($service.Status)" -ForegroundColor Green

    if ($service.Status -ne "Running") {

        Write-Host ""
        Write-Host "WARNING: Service exists but is not running." `
            -ForegroundColor Yellow

        Write-Host "Current state: $($service.Status)" `
            -ForegroundColor Yellow

        Write-Host ""
        Write-Host "Service configuration:" `
            -ForegroundColor Cyan

        & sc.exe qc $ServiceName
    }

}
else {

    Write-Host ""
    Write-Host "  Service      : skipped (--NoService)" `
        -ForegroundColor Yellow
}

# ---------------------------------------------------------
# FINAL INSTALLATION MESSAGE
# ---------------------------------------------------------

Write-Host ""
Write-Host "ULPF Agent installation completed." `
    -ForegroundColor Green

Write-Host "  Install : $InstallDir"
Write-Host "  Data    : $DataDir"
Write-Host "  Config  : $configPath"

Write-Host ""

if (-not $NoService) {

    $finalService = Get-Service `
        -Name $ServiceName `
        -ErrorAction SilentlyContinue

    if ($finalService -and $finalService.Status -eq "Running") {

        Write-Host "ULPF Agent service is RUNNING." `
            -ForegroundColor Green

    }
    else {

        Write-Host "ULPF Agent service is NOT RUNNING." `
            -ForegroundColor Yellow

    }
}

Write-Host ""
Write-Host "Next step: run the ULPF Agent discovery command." `
    -ForegroundColor Yellow
```
